### ISSUE TITLE
PHP standards

### ISSUE THREAD

**Issue by dkarlovi** [iota-community/iota.php#1]
Hello, thanks for working on this!

Seems a few common PHP standards are not followed in this package:

1. PSR-0 / PSR-4 autoloading structure
2. No Composer support, requires 1.
3. PSR-2 / PSR-12 coding style
4. [PDS skeleton guidelines](https://github.com/php-pds/skeleton)
5. unit tests, mutation tests
6. static analysis

Do you feel this is something you're interested in as a general direction?

**Comment by StefanSeehaus** [comment]
Thank you for the information, we will take this into account if it has not already been implemented or is in process
