### ISSUE TITLE
Conflicting The message has a conflict and will not be included in the ledger.

### ISSUE THREAD

**Issue by webgreat** [iota-community/iota.php#3]
Great library 👍 
Anyone have an idea why that is?

https://explorer.iota.org/mainnet/message/57ccda55ca0f4f0e4ba90c9469cdb4606fc7d829cc92671b036428f4365a35f3

**Comment by StefanSeehaus** [comment]
Thx,
Error: "The dust allowance for the address is invalid"

You are trying to send 100i, the dust protection means it must be at least 1mi (1000i)

Join our Discord, if you need some help ;-)
https://github.com/iota-community/iota.php/blob/main/help/100_Troubleshooting.md


Please use the devnet for testing. To get funds: 
https://github.com/iota-community/iota.php/blob/main/help/004_examples_faucet.md 
or use the page: https://faucet.chrysalis-devnet.iota.cafe/
