### ISSUE TITLE
searchAdresses cannot search AddressIndexes if AccountIndex is zero

### ISSUE THREAD

**Issue by kaktus2** [iota-community/iota.php#4]
If you want to search adresses only from index 0 you have to select "1" but like in the other functions it would better to be able select index zero with a "0"

As example 
`$found = $wallet->searchAddresses(0,5, false);`
would return nothing as well as i want to search for the first adrreses of indexes
`$found = $wallet->searchAddresses(5,0, false);`

You can see my solution below for that problem:
```
public function searchAddresses(int $maxAccountIndex = 5, int $maxAddressIndex = 5, bool $zeroBalance = false): array { 
   $_ret = []; 
   for($_i = 0; $_i <= $maxAccountIndex; $_i++) { 
     for($_j = 0; $_j <= $maxAddressIndex; $_j++) { 
       $_r = $this->address($_i, $_j); 
       if(($_r->getBalance()) == 0 && $zeroBalance == false) { 
         continue; 
       } 
       $_ret[] = $_r->__toArray(); 
     } 
   } 
  
   return $_ret; 
 } 
```

https://github.com/iota-community/iota.php/blob/c9e85779d313eaeaa0b22920e6e2e8d2d0c1f734/src/Wallet.php#L105-L118

**Comment by StefanSeehaus** [comment]
Thank you, change would be accepted ;-)
